### ISSUE TITLE
Trying to install this but I don't see it in the Menu

### ISSUE THREAD

**Issue by julianxhokaxhiu** [a5huynh/systemd-sublime-syntax#1]
Hi,

I just downloaded this package, I placed the folder inside `C:\Users\Julian\AppData\Roaming\Sublime Text 3\Packages`, I opened Sublime Text but I don't see it in the menu.

![list](https://cloud.githubusercontent.com/assets/1237070/14520308/0de8e75a-0224-11e6-87e7-8a7dbf184325.png)

Why? Thanks in advance!

**Comment by carsonoid** [comment]
You need to use a compiled tmLanguage file instead of the yaml format. You can use the one from my fork: https://github.com/carsonoid/systemd-sublime-syntax/blob/master/systemd.tmLanguage while I wait for PR #2  to merge.

**Comment by a5huynh** [comment]
hey @julianxhokaxhiu, you should be able to use it now.

**Comment by julianxhokaxhiu** [comment]
Thank you, I'll try it later!
